platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'MJRefresh', '~> 2.4.7'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'JSONModel', '~> 1.0.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'IQKeyboardManager'
pod 'AMapLocation'
pod 'AMap2DMap', '~> 2.5.0'
pod 'HMSegmentedControl@kennygunie', '~> 1.4.2'
pod 'DTCoreText', '~> 1.6.17'